apiVersion: v1
kind: Secret
metadata:
  name: github-ops
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/wuerzelchen/operations-deployment-prod
---
apiVersion: v1
kind: Secret
metadata:
  name: github-dev
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/wuerzelchen/project-deployment-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: helm-oci
  url: wkshp9quqv.azurecr.io
  enableOCI: "true"
  username: wkshp9quqv
  password: 9idh894Pwblj6W/ITY5xLUnFy87eJET8Y9Y+LkgVcY+ACRDsBcLV
