apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operations-deployment-prod
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: .
    repoURL: "https://github.com/wuerzelchen/operations-deployment-prod"
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
